import type { NextPage } from 'next';
import Head from 'next/head';
import { Layout } from 'components';

const Home: NextPage = () => (
  <div>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <div>
        <h1>Products</h1>
        <ul>
          <li>Product 1</li>
          <li>Product 2</li>
          <li>Product 3</li>
          <li>Product 3</li>
        </ul>
      </div>
    </Layout>
  </div>
);

export default Home;
